name: NIR blood vessel image denoise images
channels:
  - defaults
dependencies:
  - matplotlib=3.7.1
  - torch=2.1.0
  - numpy=1.25.0
  - pip=23.2.1
  - python=3.11.4
  - pillow=9.4.0
  - opencv-python=4.8.1
  - scipy=1.11.1
  - napari=0.4.19
  - PyQt5=5.15.7
  - scikit-image=0.22.0
  - tifffile=2023.12.9